### ISSUE TITLE
ValidationFor Optional

### ISSUE THREAD

**Issue by TrailBlazor** [chrissainty/BuildingCustomInputComponentsForBlazorUsingInputBase#2]
Chris, is there a way to make the ValidationFor optional? I still might want the validation to show in the ValidationSummary.

Thanks,
Dave

**Comment by chrissainty** [comment]
Just wrap it in an if statement and control that via a parameter or some other value. Should work just fine.

**Comment by TrailBlazor** [comment]
Will do. Thank you for all your work. I really appreciate it.
