### ISSUE TITLE
Simplification of SwInputText

### ISSUE THREAD

**Issue by Timores** [chrissainty/BuildingCustomInputComponentsForBlazorUsingInputBase#3]
Hi,

Thanks a lot for SwInputText. Very useful.

There is actually no need for the ValidationFor parameter. 
Since the component inherits from InputBase, there is "ValueExpression" already.

Something like:

`<ValidationMessage For="@ValueExpression" />`

(Note that removing the @ in the attribute value works, too. This part of the Blazor syntax eludes me, even though I have your book :-))

**Comment by chrissainty** [comment]
Hi @Timores. Great point. In the context of this article that would be a great optimisation.

The article was originally based off of a set of components I built for my job at the time. In those components validation was optional, and declaring the Validation expression was the signal to add the ValidationMessage component. It could have been a Boolean, that was just the route I went at the time.
